#!/bin/bash

# make an array with files in which space are replaced.
#MKV=($(ls *.mkv | sed 's/\ /_/g'))
#SMI=($(ls *.smi | sed 's/\ /_/g'))
#SMI=("$(ls *.srt)")
SMI=("$(ls | egrep '\.srt$|\.smi$')")

index=0
for FILE in *.mkv
do
    echo "${FILE}"
    echo "${SMI[$index]}"
    echo
    ((index++))
    #FILE=${FILE%.mkv}
done

echo "--------------------------------------------------"
read -n1 -p "Are files matched? (y or n) "; echo; echo
case $REPLY in
    [yY]) true
        ;;
    *) exit
        ;;
esac

index=0
for FILE in *.mkv
do
    extension="${SMI[$index]##*.}"
    mv "${SMI[$index]}" "${FILE%.mkv}.${extension}"
    ((index++))
done

