#!/bin/bash

# A simple tool which re-name subtitles based on movie files
# Author : Yeongmin Kim <yeongmin.kim@gmail.com>
# Created : 2013-01-12
# Version : 0.1

# make an array with files, srt and smi 
sub=("$(ls | egrep '\.srt$|\.smi$')")

index=0
for FILE in *.mkv
do
    echo "${FILE}"
    echo "${sub[$index]}"
    echo
    ((index++))
    #FILE=${FILE%.mkv}
done

echo "--------------------------------------------------"
read -n1 -p "Are files matched? (y or n) "; echo; echo
case $REPLY in
    [yY]) true
        ;;
    *) exit
        ;;
esac

index=0
for FILE in *.mkv
do
    extension="${sub[$index]##*.}"
    mv "${sub[$index]}" "${FILE%.mkv}.${extension}"
    ((index++))
done

